
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_NANO_SoC_GHRD(

    //////////// CLOCK //////////
    input               FPGA_CLK1_50,
    //////////// HPS //////////
    output   [14: 0]    HPS_DDR3_ADDR,
    output   [ 2: 0]    HPS_DDR3_BA,
    output              HPS_DDR3_CAS_N,
    output              HPS_DDR3_CK_N,
    output              HPS_DDR3_CK_P,
    output              HPS_DDR3_CKE,
    output              HPS_DDR3_CS_N,
    output   [ 3: 0]    HPS_DDR3_DM,
    inout    [31: 0]    HPS_DDR3_DQ,
    inout    [ 3: 0]    HPS_DDR3_DQS_N,
    inout    [ 3: 0]    HPS_DDR3_DQS_P,
    output              HPS_DDR3_ODT,
    output              HPS_DDR3_RAS_N,
    output              HPS_DDR3_RESET_N,
    input               HPS_DDR3_RZQ,
    output              HPS_DDR3_WE_N,
    input               HPS_UART_RX,
    output              HPS_UART_TX,

    //////////// LED //////////
    output   [ 7: 0]    LED,

    //////////// SW //////////
	input 	 [3:0]		SW,

    //////////// GPIO_0, GPIO connect to GPIO Default //////////
	inout    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO connect to GPIO Default //////////
	inout    [35:0]		GPIO_1
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire hps_fpga_reset_n;
wire     [2: 0]     hps_reset_req;
wire                hps_cold_reset;
wire                hps_warm_reset;
wire                hps_debug_reset;
wire                fpga_clk_50;
// connection of internal logics
assign fpga_clk_50 = FPGA_CLK1_50;

wire clk_frontend, clk_frontend_locked;
wire [1:0] I, Q;
wire SHDN_B, IDLE_B;
wire SCLK, CS_B, SDATA;
wire connection_check;

wire [1:0] ctrl_parallel_search;

wire [7:0] LED_serial, LED_parallel;

wire in_valid;
wire [1:0] I_sync, Q_sync;
wire [3:0] DI_FIFO_CDC, DO_FIFO_CDC;
wire wrreq_FIFO_CDC, rdreq_FIFO_CDC;
wire wrfull_FIFO_CDC, rdempty_FIFO_CDC;

//=======================================================
//  Structural coding
//=======================================================
assign GPIO_0 = {36{1'bz}};
// FrontEnd - Unbuffered Signal
// assign clk_frontend = GPIO_1[2];
// assign clk_frontend_locked = GPIO_1[8];
// assign I = {GPIO_1[3], GPIO_1[5]};
// assign Q = {GPIO_1[7], GPIO_1[9]};

// FrontEnd - Buffered Signal(Input)
genvar i;
generate
    for(i=0;i<36;i=i+1) begin:gpio_1_input
        if((i!=6) && (i!=10) && (i!=12) && (i!=14) && (i!=16)) begin
            assign GPIO_1[i] = 1'bz;
        end
    end
endgenerate

assign clk_frontend = GPIO_1[19];
assign clk_frontend_locked = GPIO_1[18]; // LD, logic high indicates PLL is locked
assign I = {GPIO_1[13], GPIO_1[11]};
assign Q = {GPIO_1[17], GPIO_1[15]};
assign connection_check = GPIO_1[4];

// FrontEnd - Buffered Signal(Output)
assign GPIO_1[10] = connection_check?SHDN_B:1'bz;
assign GPIO_1[6]  = connection_check?IDLE_B:1'bz;

// SPI Controller(Output)
assign GPIO_1[12] = connection_check?SCLK:1'bz;
assign GPIO_1[14] = connection_check?CS_B:1'bz;
assign GPIO_1[16] = connection_check?SDATA:1'bz;

soc_system u0(
    //Clock
    .clk_clk(FPGA_CLK1_50),                                      //                            clk.clk
    // Reset
    .reset_reset_n(hps_fpga_reset_n),                            //                          reset.reset_n
    .hps_0_h2f_reset_reset_n(hps_fpga_reset_n),                  //                hps_0_h2f_reset.reset_n
    .hps_0_f2h_cold_reset_req_reset_n(~hps_cold_reset),          //       hps_0_f2h_cold_reset_req.reset_n
    .hps_0_f2h_warm_reset_req_reset_n(~hps_warm_reset),          //       hps_0_f2h_warm_reset_req.reset_n
    .hps_0_f2h_debug_reset_req_reset_n(~hps_debug_reset),        //      hps_0_f2h_debug_reset_req.reset_n
    //HPS ddr3
    .memory_mem_a(HPS_DDR3_ADDR),                                //                         memory.mem_a
    .memory_mem_ba(HPS_DDR3_BA),                                 //                               .mem_ba
    .memory_mem_ck(HPS_DDR3_CK_P),                               //                               .mem_ck
    .memory_mem_ck_n(HPS_DDR3_CK_N),                             //                               .mem_ck_n
    .memory_mem_cke(HPS_DDR3_CKE),                               //                               .mem_cke
    .memory_mem_cs_n(HPS_DDR3_CS_N),                             //                               .mem_cs_n
    .memory_mem_ras_n(HPS_DDR3_RAS_N),                           //                               .mem_ras_n
    .memory_mem_cas_n(HPS_DDR3_CAS_N),                           //                               .mem_cas_n
    .memory_mem_we_n(HPS_DDR3_WE_N),                             //                               .mem_we_n
    .memory_mem_reset_n(HPS_DDR3_RESET_N),                       //                               .mem_reset_n
    .memory_mem_dq(HPS_DDR3_DQ),                                 //                               .mem_dq
    .memory_mem_dqs(HPS_DDR3_DQS_P),                             //                               .mem_dqs
    .memory_mem_dqs_n(HPS_DDR3_DQS_N),                           //                               .mem_dqs_n
    .memory_mem_odt(HPS_DDR3_ODT),                               //                               .mem_odt
    .memory_mem_dm(HPS_DDR3_DM),                                 //                               .mem_dm
    .memory_oct_rzqin(HPS_DDR3_RZQ),                             //                               .oct_rzqin
    // UART0 Controller
    .hps_0_hps_io_hps_io_uart0_inst_RX             (HPS_UART_RX),//                   hps_0_hps_io.hps_io_uart0_inst_RX
    .hps_0_hps_io_hps_io_uart0_inst_TX             (HPS_UART_TX),//                               .hps_io_uart0_inst_TX
    // Serial Search
    .gps_baseband_0_in_valid_conduit               (in_valid),             //                gps_baseband_0_in_valid.conduit
    .gps_baseband_0_if_i_conduit                   (I_sync),               //                    gps_baseband_0_if_i.conduit
    .gps_baseband_0_if_q_conduit                   (Q_sync),               //                    gps_baseband_0_if_q.conduit
    .gps_baseband_0_led_conduit                    (LED_serial),           //                     gps_baseband_0_led.conduit
    .gps_baseband_0_ctrl_parallel_search_conduit   (ctrl_parallel_search), //    gps_baseband_0_ctrl_parallel_search.conduit
    // Parallel Search
    .parallel_search_0_in_valid_conduit            (in_valid),             //             parallel_search_0_in_valid.conduit
    .parallel_search_0_if_i_conduit                (I_sync),               //                 parallel_search_0_if_i.conduit
    .parallel_search_0_if_q_conduit                (Q_sync),               //                 parallel_search_0_if_q.conduit
    .parallel_search_0_led_conduit                 (LED_parallel),         //                  parallel_search_0_led.conduit
    .parallel_search_0_ctrl_parallel_search_conduit(ctrl_parallel_search), // parallel_search_0_ctrl_parallel_search.conduit
    // MAX2769
    .max2769_0_is_frontend_connected_conduit(connection_check),   // max2769_0_is_frontend_connected.conduit
    .max2769_0_clk_frontend_locked_conduit(clk_frontend_locked),  //   max2769_0_clk_frontend_locked.conduit
    .max2769_0_shdn_b_conduit(SHDN_B),                            //                max2769_0_shdn_b.conduit
    .max2769_0_idle_b_conduit(IDLE_B),                            //                max2769_0_idle_b.conduit
    // SPI Controller
    .spi_0_external_SCLK                           (SCLK),        //                                .SCLK
    .spi_0_external_MOSI                           (SDATA),       //                                .MOSI
    .spi_0_external_SS_n                           (CS_B)         //                                .SS_n
);

assign LED = SW[3]?LED_serial:LED_parallel;

// Front-End Synchronizer
// Input clock frequency: 16.368 MHz
// Output clock frequency: 50 MHz
// MAX2769, clk_frontend/sign/mag
// Notice: data(sign/mag) change at positive edge, and sample at negedge edge
assign DI_FIFO_CDC = {I, Q};
assign I_sync = DO_FIFO_CDC[2+:2];
assign Q_sync = DO_FIFO_CDC[0+:2];
assign wrreq_FIFO_CDC = (clk_frontend_locked & !wrfull_FIFO_CDC);
assign rdreq_FIFO_CDC = (!rdempty_FIFO_CDC);
assign in_valid = (!rdempty_FIFO_CDC);
FIFO_CDC u_FIFO_CDC(
	.wrclk(~clk_frontend),
	.wrreq(wrreq_FIFO_CDC),
	.data(DI_FIFO_CDC),
	.rdclk(fpga_clk_50),
	.rdreq(rdreq_FIFO_CDC),
	.q(DO_FIFO_CDC),
	.rdempty(rdempty_FIFO_CDC),
	.wrfull(wrfull_FIFO_CDC)
);

// Source/Probe megawizard instance
hps_reset hps_reset_inst(
    .source_clk(fpga_clk_50),
    .source(hps_reset_req)
);

altera_edge_detector 
#(.PULSE_EXT(6), .EDGE_TYPE(1), .IGNORE_RST_WHILE_BUSY(1))
pulse_cold_reset(
    .clk(fpga_clk_50),
    .rst_n(hps_fpga_reset_n),
    .signal_in(hps_reset_req[0]),
    .pulse_out(hps_cold_reset)
);

altera_edge_detector 
#(.PULSE_EXT(2), .EDGE_TYPE(1), .IGNORE_RST_WHILE_BUSY(1))
pulse_warm_reset(
    .clk(fpga_clk_50),
    .rst_n(hps_fpga_reset_n),
    .signal_in(hps_reset_req[1]),
    .pulse_out(hps_warm_reset)
);

altera_edge_detector 
#(.PULSE_EXT(32), .EDGE_TYPE(1), .IGNORE_RST_WHILE_BUSY(1))
pulse_debug_reset(
    .clk(fpga_clk_50),
    .rst_n(hps_fpga_reset_n),
    .signal_in(hps_reset_req[2]),
    .pulse_out(hps_debug_reset)
);
endmodule
