#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.swinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'gps_baseband_0', class 'gps_baseband'
 * The macros are prefixed with 'GPS_BASEBAND_0_'.
 * The prefix is the slave descriptor.
 */
#define GPS_BASEBAND_0_COMPONENT_TYPE gps_baseband
#define GPS_BASEBAND_0_COMPONENT_NAME gps_baseband_0
#define GPS_BASEBAND_0_BASE 0x0
#define GPS_BASEBAND_0_SPAN 1024
#define GPS_BASEBAND_0_END 0x3ff

/*
 * Macros for device 'parallel_search_0', class 'parallel_search'
 * The macros are prefixed with 'PARALLEL_SEARCH_0_'.
 * The prefix is the slave descriptor.
 */
#define PARALLEL_SEARCH_0_COMPONENT_TYPE parallel_search
#define PARALLEL_SEARCH_0_COMPONENT_NAME parallel_search_0
#define PARALLEL_SEARCH_0_BASE 0x400
#define PARALLEL_SEARCH_0_SPAN 1024
#define PARALLEL_SEARCH_0_END 0x7ff

/*
 * Macros for device 'spi_0', class 'altera_avalon_spi'
 * The macros are prefixed with 'SPI_0_'.
 * The prefix is the slave descriptor.
 */
#define SPI_0_COMPONENT_TYPE altera_avalon_spi
#define SPI_0_COMPONENT_NAME spi_0
#define SPI_0_BASE 0x800
#define SPI_0_SPAN 32
#define SPI_0_END 0x81f
#define SPI_0_IRQ 2
#define SPI_0_CLOCKMULT 1
#define SPI_0_CLOCKPHASE 0
#define SPI_0_CLOCKPOLARITY 0
#define SPI_0_CLOCKUNITS "Hz"
#define SPI_0_DATABITS 32
#define SPI_0_DATAWIDTH 32
#define SPI_0_DELAYMULT "1.0E-9"
#define SPI_0_DELAYUNITS "ns"
#define SPI_0_EXTRADELAY 0
#define SPI_0_INSERT_SYNC 0
#define SPI_0_ISMASTER 1
#define SPI_0_LSBFIRST 0
#define SPI_0_NUMSLAVES 1
#define SPI_0_PREFIX "spi_"
#define SPI_0_SYNC_REG_DEPTH 2
#define SPI_0_TARGETCLOCK 50000
#define SPI_0_TARGETSSDELAY "0.0"

/*
 * Macros for device 'max2769_0', class 'max2769'
 * The macros are prefixed with 'MAX2769_0_'.
 * The prefix is the slave descriptor.
 */
#define MAX2769_0_COMPONENT_TYPE max2769
#define MAX2769_0_COMPONENT_NAME max2769_0
#define MAX2769_0_BASE 0x820
#define MAX2769_0_SPAN 16
#define MAX2769_0_END 0x82f


#endif /* _ALTERA_HPS_0_H_ */
