# TCL File Generated by Component Editor 21.1
# Tue Jan 27 12:19:06 CST 2026
# DO NOT MODIFY


# 
# max2769 "max2769" v1.0
#  2026.01.27.12:19:06
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module max2769
# 
set_module_property DESCRIPTION ""
set_module_property NAME max2769
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME max2769
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL max2769_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file max2769_bridge.v VERILOG PATH max2769/max2769_bridge.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset rst_n
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rst_n
# 
add_interface rst_n reset end
set_interface_property rst_n associatedClock clock
set_interface_property rst_n synchronousEdges DEASSERT
set_interface_property rst_n ENABLED true
set_interface_property rst_n EXPORT_OF ""
set_interface_property rst_n PORT_NAME_MAP ""
set_interface_property rst_n CMSIS_SVD_VARIABLES ""
set_interface_property rst_n SVD_ADDRESS_GROUP ""

add_interface_port rst_n rst_n reset_n Input 1


# 
# connection point SHDN_B
# 
add_interface SHDN_B conduit end
set_interface_property SHDN_B associatedClock clock
set_interface_property SHDN_B associatedReset ""
set_interface_property SHDN_B ENABLED true
set_interface_property SHDN_B EXPORT_OF ""
set_interface_property SHDN_B PORT_NAME_MAP ""
set_interface_property SHDN_B CMSIS_SVD_VARIABLES ""
set_interface_property SHDN_B SVD_ADDRESS_GROUP ""

add_interface_port SHDN_B SHDN_B conduit Output 1


# 
# connection point IDLE_B
# 
add_interface IDLE_B conduit end
set_interface_property IDLE_B associatedClock clock
set_interface_property IDLE_B associatedReset ""
set_interface_property IDLE_B ENABLED true
set_interface_property IDLE_B EXPORT_OF ""
set_interface_property IDLE_B PORT_NAME_MAP ""
set_interface_property IDLE_B CMSIS_SVD_VARIABLES ""
set_interface_property IDLE_B SVD_ADDRESS_GROUP ""

add_interface_port IDLE_B IDLE_B conduit Output 1


# 
# connection point clk_frontend_locked
# 
add_interface clk_frontend_locked conduit end
set_interface_property clk_frontend_locked associatedClock clock
set_interface_property clk_frontend_locked associatedReset ""
set_interface_property clk_frontend_locked ENABLED true
set_interface_property clk_frontend_locked EXPORT_OF ""
set_interface_property clk_frontend_locked PORT_NAME_MAP ""
set_interface_property clk_frontend_locked CMSIS_SVD_VARIABLES ""
set_interface_property clk_frontend_locked SVD_ADDRESS_GROUP ""

add_interface_port clk_frontend_locked clk_frontend_locked conduit Input 1


# 
# connection point is_frontend_connected
# 
add_interface is_frontend_connected conduit end
set_interface_property is_frontend_connected associatedClock clock
set_interface_property is_frontend_connected associatedReset ""
set_interface_property is_frontend_connected ENABLED true
set_interface_property is_frontend_connected EXPORT_OF ""
set_interface_property is_frontend_connected PORT_NAME_MAP ""
set_interface_property is_frontend_connected CMSIS_SVD_VARIABLES ""
set_interface_property is_frontend_connected SVD_ADDRESS_GROUP ""

add_interface_port is_frontend_connected is_frontend_connected conduit Input 1

