# TCL File Generated by Component Editor 25.1
# Tue Mar 24 19:41:13 CST 2026
# DO NOT MODIFY


# 
# parallel_search "parallel_search" v1.0
#  2026.03.24.19:41:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module parallel_search
# 
set_module_property DESCRIPTION ""
set_module_property NAME parallel_search
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME parallel_search
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL parallel_search_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file parallel_search_bridge.v VERILOG PATH parallel_search/parallel_search_bridge.v TOP_LEVEL_FILE
add_fileset_file parallel_search.v VERILOG PATH parallel_search/parallel_search.v
add_fileset_file signal_processing.v VERILOG PATH parallel_search/signal_processing.v
add_fileset_file controller_ft_input.v VERILOG PATH parallel_search/controller_ft_input.v
add_fileset_file controller_ft_output.v VERILOG PATH parallel_search/controller_ft_output.v
add_fileset_file correlation.v VERILOG PATH parallel_search/correlation.v
add_fileset_file correlation_processing.v VERILOG PATH parallel_search/correlation_processing.v
add_fileset_file convolution.v VERILOG PATH parallel_search/convolution.v
add_fileset_file DigitReverse.v VERILOG PATH parallel_search/DigitReverse.v
add_fileset_file CACode_generator.v VERILOG PATH parallel_search/CACode_generator.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 8
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point LED
# 
add_interface LED conduit end
set_interface_property LED associatedClock clock
set_interface_property LED associatedReset reset_sink
set_interface_property LED ENABLED true
set_interface_property LED EXPORT_OF ""
set_interface_property LED PORT_NAME_MAP ""
set_interface_property LED CMSIS_SVD_VARIABLES ""
set_interface_property LED SVD_ADDRESS_GROUP ""

add_interface_port LED LED conduit Output 8


# 
# connection point if_I
# 
add_interface if_I conduit end
set_interface_property if_I associatedClock clock
set_interface_property if_I associatedReset reset_sink
set_interface_property if_I ENABLED true
set_interface_property if_I EXPORT_OF ""
set_interface_property if_I PORT_NAME_MAP ""
set_interface_property if_I CMSIS_SVD_VARIABLES ""
set_interface_property if_I SVD_ADDRESS_GROUP ""

add_interface_port if_I I conduit Input 2


# 
# connection point if_Q
# 
add_interface if_Q conduit end
set_interface_property if_Q associatedClock clock
set_interface_property if_Q associatedReset reset_sink
set_interface_property if_Q ENABLED true
set_interface_property if_Q EXPORT_OF ""
set_interface_property if_Q PORT_NAME_MAP ""
set_interface_property if_Q CMSIS_SVD_VARIABLES ""
set_interface_property if_Q SVD_ADDRESS_GROUP ""

add_interface_port if_Q Q conduit Input 2


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset_sink
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1


# 
# connection point in_valid
# 
add_interface in_valid conduit end
set_interface_property in_valid associatedClock clock
set_interface_property in_valid associatedReset ""
set_interface_property in_valid ENABLED true
set_interface_property in_valid EXPORT_OF ""
set_interface_property in_valid PORT_NAME_MAP ""
set_interface_property in_valid CMSIS_SVD_VARIABLES ""
set_interface_property in_valid SVD_ADDRESS_GROUP ""

add_interface_port in_valid in_valid conduit Input 1


# 
# connection point ctrl_parallel_search
# 
add_interface ctrl_parallel_search conduit end
set_interface_property ctrl_parallel_search associatedClock clock
set_interface_property ctrl_parallel_search associatedReset ""
set_interface_property ctrl_parallel_search ENABLED true
set_interface_property ctrl_parallel_search EXPORT_OF ""
set_interface_property ctrl_parallel_search PORT_NAME_MAP ""
set_interface_property ctrl_parallel_search CMSIS_SVD_VARIABLES ""
set_interface_property ctrl_parallel_search SVD_ADDRESS_GROUP ""

add_interface_port ctrl_parallel_search ctrl_parallel_search conduit Output 2

