# TCL File Generated by Component Editor 25.1
# Tue Mar 31 21:28:47 CST 2026
# DO NOT MODIFY


# 
# gps_baseband "gps_baseband" v1.0
#  2026.03.31.21:28:47
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module gps_baseband
# 
set_module_property DESCRIPTION ""
set_module_property NAME gps_baseband
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME gps_baseband
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gps_baseband_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file accumulator.v VERILOG PATH serial_search/accumulator.v
add_fileset_file accumulator_two_inputs.v VERILOG PATH serial_search/accumulator_two_inputs.v
add_fileset_file carrier_mixer.v VERILOG PATH serial_search/carrier_mixer.v
add_fileset_file carrier_nco.v VERILOG PATH serial_search/carrier_nco.v
add_fileset_file code_gen.v VERILOG PATH serial_search/code_gen.v
add_fileset_file code_nco.v VERILOG PATH serial_search/code_nco.v
add_fileset_file epoch_counter.v VERILOG PATH serial_search/epoch_counter.v
add_fileset_file gps_baseband.sv SYSTEM_VERILOG PATH serial_search/gps_baseband.sv
add_fileset_file namuro_gnss_setup.v VERILOG PATH serial_search/namuro_gnss_setup.v
add_fileset_file time_base.v VERILOG PATH serial_search/time_base.v
add_fileset_file tracking_channel.v VERILOG PATH serial_search/tracking_channel.v
add_fileset_file gps_baseband_bridge.sv SYSTEM_VERILOG PATH serial_search/gps_baseband_bridge.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter num_channel INTEGER 13 ""
set_parameter_property num_channel DEFAULT_VALUE 13
set_parameter_property num_channel DISPLAY_NAME num_channel
set_parameter_property num_channel TYPE INTEGER
set_parameter_property num_channel UNITS None
set_parameter_property num_channel ALLOWED_RANGES -2147483648:2147483647
set_parameter_property num_channel DESCRIPTION ""
set_parameter_property num_channel HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset hw_rst_n
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 address address Input 8
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point LED
# 
add_interface LED conduit end
set_interface_property LED associatedClock clock
set_interface_property LED associatedReset hw_rst_n
set_interface_property LED ENABLED true
set_interface_property LED EXPORT_OF ""
set_interface_property LED PORT_NAME_MAP ""
set_interface_property LED CMSIS_SVD_VARIABLES ""
set_interface_property LED SVD_ADDRESS_GROUP ""

add_interface_port LED LED conduit Output 8


# 
# connection point hw_rst_n
# 
add_interface hw_rst_n reset end
set_interface_property hw_rst_n associatedClock clock
set_interface_property hw_rst_n synchronousEdges DEASSERT
set_interface_property hw_rst_n ENABLED true
set_interface_property hw_rst_n EXPORT_OF ""
set_interface_property hw_rst_n PORT_NAME_MAP ""
set_interface_property hw_rst_n CMSIS_SVD_VARIABLES ""
set_interface_property hw_rst_n SVD_ADDRESS_GROUP ""

add_interface_port hw_rst_n hw_rst_n reset_n Input 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset hw_rst_n
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1


# 
# connection point if_I
# 
add_interface if_I conduit end
set_interface_property if_I associatedClock clock
set_interface_property if_I associatedReset hw_rst_n
set_interface_property if_I ENABLED true
set_interface_property if_I EXPORT_OF ""
set_interface_property if_I PORT_NAME_MAP ""
set_interface_property if_I CMSIS_SVD_VARIABLES ""
set_interface_property if_I SVD_ADDRESS_GROUP ""

add_interface_port if_I I conduit Input 2


# 
# connection point if_Q
# 
add_interface if_Q conduit end
set_interface_property if_Q associatedClock clock
set_interface_property if_Q associatedReset hw_rst_n
set_interface_property if_Q ENABLED true
set_interface_property if_Q EXPORT_OF ""
set_interface_property if_Q PORT_NAME_MAP ""
set_interface_property if_Q CMSIS_SVD_VARIABLES ""
set_interface_property if_Q SVD_ADDRESS_GROUP ""

add_interface_port if_Q Q conduit Input 2


# 
# connection point in_valid
# 
add_interface in_valid conduit end
set_interface_property in_valid associatedClock clock
set_interface_property in_valid associatedReset ""
set_interface_property in_valid ENABLED true
set_interface_property in_valid EXPORT_OF ""
set_interface_property in_valid PORT_NAME_MAP ""
set_interface_property in_valid CMSIS_SVD_VARIABLES ""
set_interface_property in_valid SVD_ADDRESS_GROUP ""

add_interface_port in_valid in_valid conduit Input 1


# 
# connection point ctrl_parallel_search
# 
add_interface ctrl_parallel_search conduit end
set_interface_property ctrl_parallel_search associatedClock clock
set_interface_property ctrl_parallel_search associatedReset ""
set_interface_property ctrl_parallel_search ENABLED true
set_interface_property ctrl_parallel_search EXPORT_OF ""
set_interface_property ctrl_parallel_search PORT_NAME_MAP ""
set_interface_property ctrl_parallel_search CMSIS_SVD_VARIABLES ""
set_interface_property ctrl_parallel_search SVD_ADDRESS_GROUP ""

add_interface_port ctrl_parallel_search ctrl_parallel_search conduit Input 2

